language: generic
before_install:
  - curl -fsSL https://get.pulumi.com/ | sh
  - export PATH=$PATH:$HOME/.pulumi/bin
script:
  - ./scripts/npm-install-dependencies.sh
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: deploy-static
      script: npm run pulumi-deploy-static
stages:
  - name: test
    if: type = pull_request OR type = push
  - name: deploy
    if: type = push AND branch = master
