Outputs:
  Site:
    Value: https://guillermolam.prismacapacity.com
  Bucket:
    Value:
      Ref: SiteBucket397A1860
  DistributionId:
    Value:
      Ref: SiteDistributionCFDistribution209CF7F5
Resources:
  SiteBucket397A1860:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: guillermolam.prismacapacity.com
      Tags:
        - Key: Author
          Value: Guillermo Lam
        - Key: Project
          Value: Prisma Capaity Assignment for Guillermo Lam
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/SiteBucket/Resource
  SiteBucketPolicy3AC1D0F8:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: SiteBucket397A1860
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - SiteBucket397A1860
                      - Arn
                  - /*
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - B73396B19A9C85BF
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - SiteBucket397A1860
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/SiteBucket/Policy/Resource
  B73396B19A9C85BF:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Created by guillermo lam
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/B73396B1/Resource
  SiteDistributionCFDistribution209CF7F5:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: origin1
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            DomainName:
              Fn::GetAtt:
                - SiteBucket397A1860
                - RegionalDomainName
            Id: origin1
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - origin-access-identity/cloudfront/
                    - Ref: B73396B19A9C85BF
        PriceClass: PriceClass_100
        Restrictions:
          GeoRestriction:
            Locations:
              - US
              - CA
              - ES
              - DE
            RestrictionType: whitelist
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Author
          Value: Guillermo Lam
        - Key: Project
          Value: Prisma Capaity Assignment for Guillermo Lam
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/SiteDistribution/CFDistribution
  DeployWithInvalidationAwsCliLayerDEDD5787:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3BucketAEADE8C7
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3VersionKeyE415415F
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3VersionKeyE415415F
      Description: /opt/awscli/aws
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/DeployWithInvalidation/AwsCliLayer/Resource
      aws:asset:path: /Users/guillermolammartin/git/prisma-challenge/node_modules/@aws-cdk/lambda-layer-awscli/lib/layer.zip
      aws:asset:property: Content
  DeployWithInvalidationCustomResourceE3FF7455:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - Ref: AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3Bucket242200C2
      SourceObjectKeys:
        - Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3VersionKeyD56EB26E
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3VersionKeyD56EB26E
      DestinationBucketName:
        Ref: SiteBucket397A1860
      Prune: true
      DistributionId:
        Ref: SiteDistributionCFDistribution209CF7F5
      DistributionPaths:
        - /*
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/DeployWithInvalidation/CustomResource/Default
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Author
          Value: Guillermo Lam
        - Key: Project
          Value: Prisma Capaity Assignment for Guillermo Lam
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3Bucket242200C2
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3Bucket242200C2
                    - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - SiteBucket397A1860
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - SiteBucket397A1860
                        - Arn
                    - /*
          - Action:
              - cloudfront:GetInvalidation
              - cloudfront:CreateInvalidation
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      Roles:
        - Ref: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3Bucket55EFA30C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3VersionKey60329B70
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3VersionKey60329B70
      Role:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
          - Arn
      Handler: index.handler
      Layers:
        - Ref: DeployWithInvalidationAwsCliLayerDEDD5787
      Runtime: python3.6
      Tags:
        - Key: Author
          Value: Guillermo Lam
        - Key: Project
          Value: Prisma Capaity Assignment for Guillermo Lam
      Timeout: 900
    DependsOn:
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource
      aws:asset:path: /Users/guillermolammartin/git/prisma-challenge/node_modules/@aws-cdk/aws-s3-deployment/lib/lambda
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.90.1,@aws-cdk/assets=1.90.1,@aws-cdk/aws-applicationautoscaling=1.90.1,@aws-cdk/aws-autoscaling-common=1.90.1,@aws-cdk/aws-certificatemanager=1.90.1,@aws-cdk/aws-cloudfront=1.90.1,@aws-cdk/aws-cloudwatch=1.90.1,@aws-cdk/aws-codeguruprofiler=1.90.1,@aws-cdk/aws-ec2=1.90.1,@aws-cdk/aws-ecr=1.90.1,@aws-cdk/aws-ecr-assets=1.90.1,@aws-cdk/aws-events=1.90.1,@aws-cdk/aws-iam=1.90.1,@aws-cdk/aws-kms=1.90.1,@aws-cdk/aws-lambda=1.90.1,@aws-cdk/aws-logs=1.90.1,@aws-cdk/aws-s3=1.90.1,@aws-cdk/aws-s3-assets=1.90.1,@aws-cdk/aws-s3-deployment=1.90.1,@aws-cdk/aws-sqs=1.90.1,@aws-cdk/aws-ssm=1.90.1,@aws-cdk/cloud-assembly-schema=1.90.1,@aws-cdk/core=1.90.1,@aws-cdk/cx-api=1.90.1,@aws-cdk/lambda-layer-awscli=1.90.1,@aws-cdk/region-info=1.90.1,jsii-runtime=node.js/v15.9.0
    Metadata:
      aws:cdk:path: PrismaCapacitycStaticSite/CDKMetadata/Default
Parameters:
  AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3BucketAEADE8C7:
    Type: String
    Description: S3 bucket for asset "e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68"
  AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68S3VersionKeyE415415F:
    Type: String
    Description: S3 key for asset version "e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68"
  AssetParameterse9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68ArtifactHashD9A515C3:
    Type: String
    Description: Artifact hash for asset "e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68"
  AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3Bucket55EFA30C:
    Type: String
    Description: S3 bucket for asset "c24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cf"
  AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfS3VersionKey60329B70:
    Type: String
    Description: S3 key for asset version "c24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cf"
  AssetParametersc24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cfArtifactHash85F58E48:
    Type: String
    Description: Artifact hash for asset "c24b999656e4fe6c609c31bae56a1cf4717a405619c3aa6ba1bc686b8c2c86cf"
  AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3Bucket242200C2:
    Type: String
    Description: S3 bucket for asset "ad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdb"
  AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbS3VersionKeyD56EB26E:
    Type: String
    Description: S3 key for asset version "ad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdb"
  AssetParametersad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdbArtifactHash4640A712:
    Type: String
    Description: Artifact hash for asset "ad463dee29e2ab0dec8d82d71988a46b7f8614d4ce5ed7d8b75e72e4abb92cdb"

